//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.WireMains = new HashSet<WireMain>();
        }
    
        public int BatchID { get; set; }
        public Nullable<System.DateTime> Opened_Time { get; set; }
        public string Opened_User { get; set; }
        public Nullable<System.DateTime> Submitted_Date { get; set; }
        public string Submitted_User { get; set; }
        public Nullable<bool> OFAC_Verified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WireMain> WireMains { get; set; }
    }
}
