//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedWireSVCInfo
    {
        public int FedWireSVCInfo_ID { get; set; }
        public string MsgDisposition_Version { get; set; }
        public string MsgDisp_ProdCode { get; set; }
        public string MsgDisp_DupCode { get; set; }
        public string MsgDisp_Status { get; set; }
        public string RcptTimeStamp_Date { get; set; }
        public string RcptTimeStamp_Time { get; set; }
        public string Rcpt_AppID { get; set; }
        public string OMAD_CycleDate { get; set; }
        public string OMAD_DestID { get; set; }
        public string OMAD_SeqNum { get; set; }
        public string OMAD_Date { get; set; }
        public string OMAD_Time { get; set; }
        public string OMAD_FRBID { get; set; }
        public string Error_Category { get; set; }
        public string Error_Code { get; set; }
        public string Error_Desc { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
