//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class FItoFI_Info
    {
        public int FItoFI_ID { get; set; }
        public string FIFI_RecInfo1 { get; set; }
        public string FIFI_RecInfo2 { get; set; }
        public string FIFI_RecInfo3 { get; set; }
        public string FIFI_RecInfo4 { get; set; }
        public string FIFI_RecInfo5 { get; set; }
        public string FIFI_RecInfo6 { get; set; }
        public string DrawDbtAdv_Code { get; set; }
        public string DrawDbtAdv_Info1 { get; set; }
        public string DrawDbtAdv_Info2 { get; set; }
        public string DrawDbtAdv_Info3 { get; set; }
        public string DrawDbtAdv_Info4 { get; set; }
        public string DrawDbtAdv_Info5 { get; set; }
        public string DrawDbtAdv_Info6 { get; set; }
        public string InterFI_Info1 { get; set; }
        public string InterFI_Info2 { get; set; }
        public string InterFI_Info3 { get; set; }
        public string InterFI_Info4 { get; set; }
        public string InterFI_Info5 { get; set; }
        public string InterFI_Info6 { get; set; }
        public string InterFIAdv_Code { get; set; }
        public string InterFIAdv_Info1 { get; set; }
        public string InterFIAdv_Info2 { get; set; }
        public string InterFIAdv_Info3 { get; set; }
        public string InterFIAdv_Info4 { get; set; }
        public string InterFIAdv_Info5 { get; set; }
        public string InterFIAdv_Info6 { get; set; }
        public string BnfFI_Info1 { get; set; }
        public string BnfFI_Info2 { get; set; }
        public string BnfFI_Info3 { get; set; }
        public string BnfFI_Info4 { get; set; }
        public string BnfFI_Info5 { get; set; }
        public string BnfFI_Info6 { get; set; }
        public string BnfFIAdv_Code { get; set; }
        public string BnfFIAdv_Info1 { get; set; }
        public string BnfFIAdv_Info2 { get; set; }
        public string BnfFIAdv_Info3 { get; set; }
        public string BnfFIAdv_Info4 { get; set; }
        public string BnfFIAdv_Info5 { get; set; }
        public string BnfFIAdv_Info6 { get; set; }
        public string MethodPmtBnf_Method { get; set; }
        public string MethodPmtBnf_Info { get; set; }
        public string FI_to_FI_Info1 { get; set; }
        public string FI_to_FI_Info2 { get; set; }
        public string FI_to_FI_Info3 { get; set; }
        public string FI_to_FI_Info4 { get; set; }
        public string FI_to_FI_Info5 { get; set; }
        public string FI_to_FI_Info6 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
