//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FWFCdbEntities : DbContext
    {
        public FWFCdbEntities()
            : base("name=FWFCdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BnfInfo> BnfInfoes { get; set; }
        public virtual DbSet<CoverPymtSeqB> CoverPymtSeqBs { get; set; }
        public virtual DbSet<FedWireSVCInfo> FedWireSVCInfoes { get; set; }
        public virtual DbSet<FItoFI_Info> FItoFI_Info { get; set; }
        public virtual DbSet<MandatoryField> MandatoryFields { get; set; }
        public virtual DbSet<OriginatorInfo> OriginatorInfoes { get; set; }
        public virtual DbSet<OtherTransferInfo> OtherTransferInfoes { get; set; }
        public virtual DbSet<RelatedRemitInfo> RelatedRemitInfoes { get; set; }
        public virtual DbSet<StructRemitOnce> StructRemitOnces { get; set; }
        public virtual DbSet<StructRemitRepeat> StructRemitRepeats { get; set; }
        public virtual DbSet<SVCInfo> SVCInfoes { get; set; }
        public virtual DbSet<UnstructAddenda> UnstructAddendas { get; set; }
        public virtual DbSet<WireMain> WireMains { get; set; }
        public virtual DbSet<WireTemplate> WireTemplates { get; set; }
        public virtual DbSet<BatchSummary> BatchSummaries { get; set; }
    }
}
