//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandatoryField
    {
        public int Mandatory_ID { get; set; }
        public string SSI_Format { get; set; }
        public string SSI_URC { get; set; }
        public string SSI_TPC { get; set; }
        public string SSI_MDC { get; set; }
        public string TypeCode { get; set; }
        public string SubType { get; set; }
        public string IMAD_ICD { get; set; }
        public string IMAD_Source { get; set; }
        public string IMAD_Seq { get; set; }
        public Nullable<decimal> WireAmount { get; set; }
        public string SenderDI_ABA { get; set; }
        public string SenderDI_ShortName { get; set; }
        public string ReceiverDI_ABA { get; set; }
        public string ReceiverDI_ShortName { get; set; }
        public string BusinessFunctionCode { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
