//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginatorInfo
    {
        public int Originator_ID { get; set; }
        public string Orig_ID { get; set; }
        public string Orig_Ident { get; set; }
        public string Orig_Name { get; set; }
        public string Orig_Addr1 { get; set; }
        public string Orig_Addr2 { get; set; }
        public string Orig_Addr3 { get; set; }
        public string Orig_Addr4 { get; set; }
        public string OrigOptF_ID { get; set; }
        public string OrigOptF_Name { get; set; }
        public string OrigOptF_L1 { get; set; }
        public string OrigOptF_L2 { get; set; }
        public string OrigOptF_L3 { get; set; }
        public string OrigFI_ID { get; set; }
        public string OrigFI_Ident { get; set; }
        public string OrigFI_Name { get; set; }
        public string OrigFI_Addr1 { get; set; }
        public string OrigFI_Addr2 { get; set; }
        public string OrigFI_Addr3 { get; set; }
        public string InstructFI_ID { get; set; }
        public string InstructFI_Ident { get; set; }
        public string InstructFI_Name { get; set; }
        public string InstructFI_Addr1 { get; set; }
        public string InstructFI_Addr2 { get; set; }
        public string InstructFI_Addr3 { get; set; }
        public string AcctCredDrawDown { get; set; }
        public string OBI_L1 { get; set; }
        public string OBI_L2 { get; set; }
        public string OBI_L3 { get; set; }
        public string OBI_L4 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
