//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedRemitInfo
    {
        public int RelRemitInfo_ID { get; set; }
        public string RelRemit_ID { get; set; }
        public string RelRemit_Loc { get; set; }
        public string RemitLoc_ElecAddr { get; set; }
        public string RelRemit_Name { get; set; }
        public string RelRemit_AddrType { get; set; }
        public string RelRemit_Dept { get; set; }
        public string RelRemit_SubDept { get; set; }
        public string RelRemit_StrName { get; set; }
        public string RelRemit_BldgNum { get; set; }
        public string RelRemit_PostCode { get; set; }
        public string RelRemit_TownName { get; set; }
        public string RelRemit_CountrySubDiv { get; set; }
        public string RelRemit_Country { get; set; }
        public string RelRemit_Addr1 { get; set; }
        public string RelRemit_Addr2 { get; set; }
        public string RelRemit_Addr3 { get; set; }
        public string RelRemit_Addr4 { get; set; }
        public string RelRemit_Addr5 { get; set; }
        public string RelRemit_Addr6 { get; set; }
        public string RelRemit_Addr7 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
