//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleID { get; set; }
        public bool CreateNewBatch { get; set; }
        public bool VerifyBatch { get; set; }
        public bool ExportBatch { get; set; }
        public bool ModifyBatch { get; set; }
        public bool DeleteBatch { get; set; }
        public bool CreateNewWire { get; set; }
        public bool VerifyWire { get; set; }
        public bool ModifyWire { get; set; }
        public bool DeleteWire { get; set; }
        public bool CreateNewTemplate { get; set; }
        public bool VerifyTemplate { get; set; }
        public bool ModifyTemplate { get; set; }
        public bool DeleteTemplate { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
