//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int SecurityID { get; set; }
        public string Question1 { get; set; }
        public string Answer1 { get; set; }
        public string Question2 { get; set; }
        public string Answer2 { get; set; }
        public string Question3 { get; set; }
        public string Answer3 { get; set; }
        public string Question4 { get; set; }
        public string Answer4 { get; set; }
        public string Question5 { get; set; }
        public string Answer5 { get; set; }
        public string SecurityPIN { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
