//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructRemitOnce
    {
        public int StructRemitOnce_ID { get; set; }
        public string RemitOrig_Type { get; set; }
        public string RemitOrig_Code { get; set; }
        public string RemitOrig_Name { get; set; }
        public string RemitOrig_IDNum { get; set; }
        public string RemitOrig_IDNumIss { get; set; }
        public string RemitOrig_Birth { get; set; }
        public string RemitOrig_AddrType { get; set; }
        public string RemitOrig_Dept { get; set; }
        public string RemitOrig_SubDept { get; set; }
        public string RemitOrig_StreetName { get; set; }
        public string RemitOrig_BldgNum { get; set; }
        public string RemitOrig_PostCode { get; set; }
        public string RemitOrig_TownName { get; set; }
        public string RemitOrig_CountrySub { get; set; }
        public string RemitOrig_Country { get; set; }
        public string RemitOrig_Addr1 { get; set; }
        public string RemitOrig_Addr2 { get; set; }
        public string RemitOrig_Addr3 { get; set; }
        public string RemitOrig_Addr4 { get; set; }
        public string RemitOrig_Addr5 { get; set; }
        public string RemitOrig_Addr6 { get; set; }
        public string RemitOrig_Addr7 { get; set; }
        public string RemitOrig_CountryRes { get; set; }
        public string RemitOrig_ContactName { get; set; }
        public string RemitOrig_PhoneNum { get; set; }
        public string RemitOrig_MobileNum { get; set; }
        public string RemitOrig_FaxNum { get; set; }
        public string RemitOrig_ContactElec { get; set; }
        public string RemitOrig_ContactOther { get; set; }
        public string RemitBnf_Name { get; set; }
        public string RemitBnf_ { get; set; }
        public string RemitBnf_Code { get; set; }
        public string RemitBnf_IDNum { get; set; }
        public string RemitBnf_IDNumIss { get; set; }
        public string RemitBnf_Birth { get; set; }
        public string RemitBnf_AddrType { get; set; }
        public string RemitBnf_Dept { get; set; }
        public string RemitBnf_SubDept { get; set; }
        public string RemitBnf_StreetName { get; set; }
        public string RemitBnf_BldgNum { get; set; }
        public string RemitBnf_PostCode { get; set; }
        public string RemitBnf_TownName { get; set; }
        public string RemitBnf_CountrySub { get; set; }
        public string RemitBnf_Country { get; set; }
        public string RemitBnf_Addr1 { get; set; }
        public string RemitBnf_Addr2 { get; set; }
        public string RemitBnf_Addr3 { get; set; }
        public string RemitBnf_Addr4 { get; set; }
        public string RemitBnf_Addr5 { get; set; }
        public string RemitBnf_Addr6 { get; set; }
        public string RemitBnf_Addr7 { get; set; }
        public string RemitBnf_CountryRes { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
