//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructRemitRepeat
    {
        public int StructRemitRepeat_ID { get; set; }
        public string PrimRemit_DocType { get; set; }
        public string PrimRemit_PropDocType { get; set; }
        public string PrimRemit_DocID { get; set; }
        public string PrimRemit_Issuer { get; set; }
        public string AmtPaid_CurrCode { get; set; }
        public string AmtPaid_Amount { get; set; }
        public string GrossAmtRemit_CurrCode { get; set; }
        public string GrossAmtRemit_Amount { get; set; }
        public string AmtNegDisc_CurrCode { get; set; }
        public string AmtNegDisc_Amount { get; set; }
        public string AdjustInfo_RsnCode { get; set; }
        public string AdjustInfo_Indicator { get; set; }
        public string AdjustInfo_CurrCode { get; set; }
        public string AdjustInfo_Amount { get; set; }
        public string AdjustInfo_Info { get; set; }
        public string DateOfRemitDoc { get; set; }
        public string SecRemit_Type { get; set; }
        public string SecRemit_PropDocType { get; set; }
        public string SecRemit_DocID { get; set; }
        public string SecRemit_Issuer { get; set; }
        public string Remit_FreeText1 { get; set; }
        public string Remit_FreeText2 { get; set; }
        public string Remit_FreeText3 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
