//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVCInfo
    {
        public int ServiceInfo_ID { get; set; }
        public string SVCInfo_L1 { get; set; }
        public string SVCInfo_L2 { get; set; }
        public string SVCInfo_L3 { get; set; }
        public string SVCInfo_L4 { get; set; }
        public string SVCInfo_L5 { get; set; }
        public string SVCInfo_L6 { get; set; }
        public string SVCInfo_L7 { get; set; }
        public string SVCInfo_L8 { get; set; }
        public string SVCInfo_L9 { get; set; }
        public string SVCInfo_L10 { get; set; }
        public string SVCInfo_L11 { get; set; }
        public string SVCInfo_L12 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
