//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedWire_Batch_File_Creator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnstructAddenda
    {
        public int Unstruct_Addenda_ID { get; set; }
        public string UA_Length { get; set; }
        public string UA_Info1 { get; set; }
        public string UA_Info2 { get; set; }
        public string UA_Info3 { get; set; }
        public string UA_Info4 { get; set; }
        public string UA_Info5 { get; set; }
        public string UA_Info6 { get; set; }
        public string UA_Info7 { get; set; }
        public string UA_Info8 { get; set; }
        public string UA_Info9 { get; set; }
        public Nullable<int> FK_WireID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
    
        public virtual WireMain WireMain { get; set; }
        public virtual WireTemplate WireTemplate { get; set; }
    }
}
